version: "3.7"
services:
  postgres:
    image: postgres:12
    restart: "no"
    ports:
      - "5432:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=amplayer
      - POSTGRES_PASSWORD=amplayerdev
      - POSTGRES_DB=tryton

  pgadmin:
    image: dpage/pgadmin4:5.2
    restart: "no"
    ports:
      - "8083:8083"
    volumes:
      - "pgadmin:/var/lib/pgadmin"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=8083

volumes:
  postgres:
  pgadmin:
