version: "3.7"
services:
  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    volumes:
      - "~/.local/amplayer/trytond/postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=amplayer
      - POSTGRES_PASSWORD=amplayerdev
      - POSTGRES_DB=tryton
